"""empty message

Revision ID: 54d6d9a24cac
Revises: a3f88336f3fb
Create Date: 2026-03-02 14:02:25.751208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d6d9a24cac'
down_revision = 'a3f88336f3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('personaje_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('nave_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('id_nave',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('id_nave',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('nave_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('personaje_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
